# Tannis McCartney
## June 17, 2022

##  Data Preparation - NS Median Income Tables  

## Table of Contents
### 01 Import Libraries
### 02 Import Dataset
### 03 Data Wrangling
### 04 Consistency Checks
### 05 Export cleaned dataframe

# 01 Import Libraries

In [1]:
# Import libraries for analysis
import pandas as pd
import numpy as np
import os

# 02 Import Datasets

In [2]:
# Turn project folder path into a string
path = r'C:\Users\tmmcc\Google Drive\Data Analytics Bootcamp\6 Advanced Analytics and Dashboard Design\Nova Scotia Housing and Income'

In [3]:
# Load housing market indicators table
NSHousing = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'housing-market-indicators-nova-scotia-1990-2016.csv'), index_col=False)
NSHousing.head()

,indicator,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,"Starts, total",5560.0,5173.0,4673.0,4282.0,4748.0,4168.0,4059.0,3813.0,3137.0,...,4750.0,3982.0,3438.0,4309.0,4644.0,4522.0,3919.0,3056.0,3825.0,3767.0
1,"Starts, Single-detached",3639.0,2604.0,3232.0,3126.0,3358.0,3040.0,3278.0,2939.0,2257.0,...,2887.0,2636.0,2193.0,2392.0,2045.0,2258.0,1639.0,1355.0,1350.0,1656.0
2,"Starts, Multiple",1921.0,2569.0,1441.0,1156.0,1390.0,1128.0,781.0,874.0,880.0,...,1863.0,1346.0,1245.0,1917.0,2599.0,2264.0,2280.0,1701.0,2475.0,2111.0
3,"Starts, Semi-detached",310.0,301.0,373.0,496.0,518.0,417.0,447.0,303.0,290.0,...,333.0,328.0,274.0,373.0,418.0,420.0,332.0,220.0,259.0,318.0
4,"Starts, Row",100.0,46.0,93.0,81.0,99.0,72.0,59.0,58.0,89.0,...,221.0,219.0,187.0,200.0,241.0,218.0,259.0,179.0,129.0,144.0

In [4]:
# Check shape of table
NSHousing.shape

(35, 28)

# 03 Data Wrangling

In [5]:
# Transpose table
df_T = NSHousing.transpose()
df_T.head()

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
indicator,"Starts, total","Starts, Single-detached","Starts, Multiple","Starts, Semi-detached","Starts, Row","Starts, Apartment","Starts by intended market, 1 total","Starts, Homeownership - freehold","Starts, Rental","Starts, Homeownership - condominium",...,Average rent ($) Bachelor,Average rent ($) One-bedroom,Average rent ($) Two-bedroom,Average rent ($) 3+ bedroom,Population on July 1 (thousands)4,Labour force participation rate (%)4,Employment (% change)5,Unemployment rate (%)4,Real disposable income (% change)5,Net migration5
1990,5560.0,3639.0,1921.0,310.0,100.0,1511.0,3650.0,2199.0,1107.0,12.0,...,391.0,460.0,539.0,658.0,910.5,61.9,1.0,10.7,NaN,NaN
1991,5173.0,2604.0,2569.0,301.0,46.0,2222.0,3681.0,1590.0,1691.0,0.0,...,408.0,481.0,565.0,690.0,915.0,61.5,-1.2,12.1,-1.5,NaN
1992,4673.0,3232.0,1441.0,373.0,93.0,975.0,3222.0,2190.0,764.0,0.0,...,409.0,475.0,562.0,687.0,919.5,60.0,-3.1,13.1,2.3,1217.0
1993,4282.0,3126.0,1156.0,496.0,81.0,579.0,2988.0,2306.0,642.0,0.0,...,412.0,482.0,571.0,719.0,923.9,60.1,-0.6,14.3,2.1,1676.0

In [6]:
# Add an index to transposed dataframe
df_T.reset_index()

,index,0,1,2,3,4,5,6,7,8,...,25,26,27,28,29,30,31,32,33,34
0,indicator,"Starts, total","Starts, Single-detached","Starts, Multiple","Starts, Semi-detached","Starts, Row","Starts, Apartment","Starts by intended market, 1 total","Starts, Homeownership - freehold","Starts, Rental",...,Average rent ($) Bachelor,Average rent ($) One-bedroom,Average rent ($) Two-bedroom,Average rent ($) 3+ bedroom,Population on July 1 (thousands)4,Labour force participation rate (%)4,Employment (% change)5,Unemployment rate (%)4,Real disposable income (% change)5,Net migration5
1,1990,5560.0,3639.0,1921.0,310.0,100.0,1511.0,3650.0,2199.0,1107.0,...,391.0,460.0,539.0,658.0,910.5,61.9,1.0,10.7,NaN,NaN
2,1991,5173.0,2604.0,2569.0,301.0,46.0,2222.0,3681.0,1590.0,1691.0,...,408.0,481.0,565.0,690.0,915.0,61.5,-1.2,12.1,-1.5,NaN
3,1992,4673.0,3232.0,1441.0,373.0,93.0,975.0,3222.0,2190.0,764.0,...,409.0,475.0,562.0,687.0,919.5,60.0,-3.1,13.1,2.3,1217.0
4,1993,4282.0,3126.0,1156.0,496.0,81.0,579.0,2988.0,2306.0,642.0,...,412.0,482.0,571.0,719.0,923.9,60.1,-0.6,14.3,2.1,1676.0
5,1994,4748.0,3358.0,1390.0,518.0,99.0,773.0,3304.0,2493.0,671.0,...,421.0,485.0,579.0,711.0,926.9,60.1,1.7,13.5,-0.8,409.0
6,1995,4168.0,3040.0,1128.0,417.0,72.0,639.0,2695.0,2098.0,570.0,...,422.0,488.0,584.0,760.0,928.1,59.4,0.9,12.2,0.3,-432.0
7,1996,4059.0,3278.0,781.0,447.0,59.0,275.0,2806.0,2527.0,279.0,...,421.0,488.0,588.0,732.0,931.3,59.4,0.2,12.4,-2.5,1475.0
8,1997,3813.0,2939.0,874.0,303.0,58.0,513.0,2732.0,2225.0,479.0,...,424.0,490.0,589.0,722.0,932.4,59.7,1.5,12.1,1.4,695.0
9,1998,3137.0,2257.0,880.0,290.0,89.0,501.0,2171.0,1664.0,418.0,...,433.0,496.0,603.0,763.0,931.8,60.5,3.6,10.5,3.8,-547.0
10,1999,4250.0,3345.0,905.0,218.0,29.0,658.0,2834.0,2263.0,571.0,...,448.0,507.0,609.0,761.0,933.8,60.8,2.0,9.6,4.4,1991.0
11,2000,4432.0,2856.0,1576.0,266.0,17.0,1293.0,3050.0,1867.0,810.0,...,468.0,522.0,621.0,773.0,933.8,61.2,2.0,9.1,-0.6,126.0
12,2001,4092.0,2761.0,1331.0,228.0,40.0,1063.0,2767.0,1765.0,746.0,...,486.0,537.0,645.0,835.0,932.5,62.0,0.9,9.7,2.8,-946.0
13,2002,4970.0,3363.0,1607.0,253.0,144.0,1210.0,3721.0,2493.0,847.0,...,499.0,555.0,669.0,897.0,935.2,62.5,1.7,9.6,2.6,1055.0
14,2003,5096.0,2968.0,2128.0,338.0,277.0,1513.0,3591.0,2219.0,833.0,...,514.0,575.0,684.0,919.0,937.7,63.0,2.1,9.1,0.0,993.0
15,2004,4717.0,3270.0,1447.0,266.0,186.0,995.0,3314.0,2310.0,559.0,...,532.0,592.0,711.0,973.0,939.6,63.9,2.4,8.8,1.5,652.0
16,2005,4775.0,3010.0,1765.0,301.0,265.0,1199.0,3257.0,2133.0,643.0,...,532.0,608.0,726.0,912.0,937.9,63.4,0.1,8.4,0.9,-2754.0
17,2006,4896.0,2757.0,2139.0,353.0,255.0,1531.0,3327.0,1941.0,1096.0,...,553.0,629.0,760.0,986.0,937.9,62.7,-0.2,7.9,3.5,-1145.0
18,2007,4750.0,2887.0,1863.0,333.0,221.0,1309.0,3320.0,2075.0,911.0,...,557.0,642.0,777.0,1030.0,935.1,63.6,1.4,8.0,2.1,-2087.0
19,2008,3982.0,2636.0,1346.0,328.0,219.0,799.0,3327.0,2509.0,647.0,...,580.0,664.0,795.0,1030.0,935.9,63.7,1.0,7.6,3.6,938.0
20,2009,3438.0,2193.0,1245.0,274.0,187.0,784.0,2787.0,2037.0,655.0,...,617.0,692.0,838.0,1056.0,938.2,64.2,-0.5,9.2,4.0,2486.0
21,2010,4309.0,2392.0,1917.0,373.0,200.0,1344.0,3538.0,2321.0,1119.0,...,612.0,713.0,851.0,1116.0,942.1,64.3,0.4,9.6,2.9,4100.0
22,2011,4644.0,2045.0,2599.0,418.0,241.0,1940.0,4075.0,2113.0,1793.0,...,647.0,730.0,882.0,1146.0,944.5,63.9,0.4,9.0,-0.2,3069.0
23,2012,4522.0,2258.0,2264.0,420.0,218.0,1626.0,3925.0,2262.0,1482.0,...,663.0,750.0,909.0,1153.0,944.9,64.4,1.0,9.1,1.6,-88.0
24,2013,3919.0,1639.0,2280.0,332.0,259.0,1689.0,3314.0,1676.0,1564.0,...,682.0,763.0,929.0,1200.0,943.5,63.7,-1.1,9.1,2.5,-1647.0
25,2014,3056.0,1355.0,1701.0,220.0,179.0,1302.0,2633.0,1326.0,1089.0,...,686.0,776.0,955.0,1231.0,943.3,62.8,-1.1,9.0,0.4,-238.0
26,2015,3825.0,1350.0,2475.0,259.0,129.0,2087.0,3448.0,1293.0,1611.0,...,702.0,807.0,992.0,1262.0,943.4,62.4,0.1,8.6,2.5,284.0
27,2016,3767.0,1656.0,2111.0,318.0,144.0,1649.0,3118.0,1397.0,1409.0,...,724.0,819.0,1008.0,1254.0,949.5,61.7,-0.4,8.3,NaN,6494.0

In [7]:
# Create a new header for transposed dataframe
new_header = df_T.iloc[0]
new_header

0                                         Starts, total
1                               Starts, Single-detached
2                                     Starts,  Multiple
3                              Starts,    Semi-detached
4                                       Starts,     Row
5                                Starts,      Apartment
6                    Starts by intended market, 1 total
7                     Starts,  Homeownership - freehold
8                                      Starts,   Rental
9                 Starts,   Homeownership - condominium
10                  Starts,   Other (co-op and unknown)
11                                   Completions, total
12                        Residential Building Permits4
13         Residential Building Permits($) (thousands)4
14         Supply, Newly completed and unabsorbed homes
15                   Supply,  Single- and semi-detached
16                            Supply, Row and apartment
17                             Rental vacancy rate (%)3
18                        Rental availability rate (%)3
19    Vacancy Rate (Standard Spaces) in Seniors' Ren...
20                  New Housing Price Index (% change)5
21                     Consumer Price Index (% change)5
22             Construction Wage Rate Index (% change)5
23                Owned accommodation costs (% change)5
24               Rental accommodation costs (% change)5
25                           Average rent ($)  Bachelor
26                        Average rent ($)  One-bedroom
27                        Average rent ($)  Two-bedroom
28                         Average rent ($)  3+ bedroom
29                    Population on July 1 (thousands)4
30                 Labour force participation rate (%)4
31                               Employment (% change)5
32                               Unemployment rate (%)4
33                   Real disposable income (% change)5
34                                       Net migration5
Name: indicator, dtype: object

In [8]:
# Create a new dataframe that starts after the first row of dataframe
df = df_T[1:]
df

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
1990,5560.0,3639.0,1921.0,310.0,100.0,1511.0,3650.0,2199.0,1107.0,12.0,...,391.0,460.0,539.0,658.0,910.5,61.9,1.0,10.7,NaN,NaN
1991,5173.0,2604.0,2569.0,301.0,46.0,2222.0,3681.0,1590.0,1691.0,0.0,...,408.0,481.0,565.0,690.0,915.0,61.5,-1.2,12.1,-1.5,NaN
1992,4673.0,3232.0,1441.0,373.0,93.0,975.0,3222.0,2190.0,764.0,0.0,...,409.0,475.0,562.0,687.0,919.5,60.0,-3.1,13.1,2.3,1217.0
1993,4282.0,3126.0,1156.0,496.0,81.0,579.0,2988.0,2306.0,642.0,0.0,...,412.0,482.0,571.0,719.0,923.9,60.1,-0.6,14.3,2.1,1676.0
1994,4748.0,3358.0,1390.0,518.0,99.0,773.0,3304.0,2493.0,671.0,0.0,...,421.0,485.0,579.0,711.0,926.9,60.1,1.7,13.5,-0.8,409.0
1995,4168.0,3040.0,1128.0,417.0,72.0,639.0,2695.0,2098.0,570.0,24.0,...,422.0,488.0,584.0,760.0,928.1,59.4,0.9,12.2,0.3,-432.0
1996,4059.0,3278.0,781.0,447.0,59.0,275.0,2806.0,2527.0,279.0,0.0,...,421.0,488.0,588.0,732.0,931.3,59.4,0.2,12.4,-2.5,1475.0
1997,3813.0,2939.0,874.0,303.0,58.0,513.0,2732.0,2225.0,479.0,0.0,...,424.0,490.0,589.0,722.0,932.4,59.7,1.5,12.1,1.4,695.0
1998,3137.0,2257.0,880.0,290.0,89.0,501.0,2171.0,1664.0,418.0,89.0,...,433.0,496.0,603.0,763.0,931.8,60.5,3.6,10.5,3.8,-547.0
1999,4250.0,3345.0,905.0,218.0,29.0,658.0,2834.0,2263.0,571.0,0.0,...,448.0,507.0,609.0,761.0,933.8,60.8,2.0,9.6,4.4,1991.0
2000,4432.0,2856.0,1576.0,266.0,17.0,1293.0,3050.0,1867.0,810.0,371.0,...,468.0,522.0,621.0,773.0,933.8,61.2,2.0,9.1,-0.6,126.0
2001,4092.0,2761.0,1331.0,228.0,40.0,1063.0,2767.0,1765.0,746.0,256.0,...,486.0,537.0,645.0,835.0,932.5,62.0,0.9,9.7,2.8,-946.0
2002,4970.0,3363.0,1607.0,253.0,144.0,1210.0,3721.0,2493.0,847.0,378.0,...,499.0,555.0,669.0,897.0,935.2,62.5,1.7,9.6,2.6,1055.0
2003,5096.0,2968.0,2128.0,338.0,277.0,1513.0,3591.0,2219.0,833.0,530.0,...,514.0,575.0,684.0,919.0,937.7,63.0,2.1,9.1,0.0,993.0
2004,4717.0,3270.0,1447.0,266.0,186.0,995.0,3314.0,2310.0,559.0,445.0,...,532.0,592.0,711.0,973.0,939.6,63.9,2.4,8.8,1.5,652.0
2005,4775.0,3010.0,1765.0,301.0,265.0,1199.0,3257.0,2133.0,643.0,481.0,...,532.0,608.0,726.0,912.0,937.9,63.4,0.1,8.4,0.9,-2754.0
2006,4896.0,2757.0,2139.0,353.0,255.0,1531.0,3327.0,1941.0,1096.0,290.0,...,553.0,629.0,760.0,986.0,937.9,62.7,-0.2,7.9,3.5,-1145.0
2007,4750.0,2887.0,1863.0,333.0,221.0,1309.0,3320.0,2075.0,911.0,334.0,...,557.0,642.0,777.0,1030.0,935.1,63.6,1.4,8.0,2.1,-2087.0
2008,3982.0,2636.0,1346.0,328.0,219.0,799.0,3327.0,2509.0,647.0,171.0,...,580.0,664.0,795.0,1030.0,935.9,63.7,1.0,7.6,3.6,938.0
2009,3438.0,2193.0,1245.0,274.0,187.0,784.0,2787.0,2037.0,655.0,95.0,...,617.0,692.0,838.0,1056.0,938.2,64.2,-0.5,9.2,4.0,2486.0
2010,4309.0,2392.0,1917.0,373.0,200.0,1344.0,3538.0,2321.0,1119.0,98.0,...,612.0,713.0,851.0,1116.0,942.1,64.3,0.4,9.6,2.9,4100.0
2011,4644.0,2045.0,2599.0,418.0,241.0,1940.0,4075.0,2113.0,1793.0,169.0,...,647.0,730.0,882.0,1146.0,944.5,63.9,0.4,9.0,-0.2,3069.0
2012,4522.0,2258.0,2264.0,420.0,218.0,1626.0,3925.0,2262.0,1482.0,181.0,...,663.0,750.0,909.0,1153.0,944.9,64.4,1.0,9.1,1.6,-88.0
2013,3919.0,1639.0,2280.0,332.0,259.0,1689.0,3314.0,1676.0,1564.0,74.0,...,682.0,763.0,929.0,1200.0,943.5,63.7,-1.1,9.1,2.5,-1647.0
2014,3056.0,1355.0,1701.0,220.0,179.0,1302.0,2633.0,1326.0,1089.0,166.0,...,686.0,776.0,955.0,1231.0,943.3,62.8,-1.1,9.0,0.4,-238.0
2015,3825.0,1350.0,2475.0,259.0,129.0,2087.0,3448.0,1293.0,1611.0,386.0,...,702.0,807.0,992.0,1262.0,943.4,62.4,0.1,8.6,2.5,284.0
2016,3767.0,1656.0,2111.0,318.0,144.0,1649.0,3118.0,1397.0,1409.0,312.0,...,724.0,819.0,1008.0,1254.0,949.5,61.7,-0.4,8.3,NaN,6494.0

In [9]:
# Add new header to new dataframe
df.columns = new_header
df

indicator,"Starts, total","Starts, Single-detached","Starts, Multiple","Starts, Semi-detached","Starts, Row","Starts, Apartment","Starts by intended market, 1 total","Starts, Homeownership - freehold","Starts, Rental","Starts, Homeownership - condominium",...,Average rent ($) Bachelor,Average rent ($) One-bedroom,Average rent ($) Two-bedroom,Average rent ($) 3+ bedroom,Population on July 1 (thousands)4,Labour force participation rate (%)4,Employment (% change)5,Unemployment rate (%)4,Real disposable income (% change)5,Net migration5
1990,5560.0,3639.0,1921.0,310.0,100.0,1511.0,3650.0,2199.0,1107.0,12.0,...,391.0,460.0,539.0,658.0,910.5,61.9,1.0,10.7,NaN,NaN
1991,5173.0,2604.0,2569.0,301.0,46.0,2222.0,3681.0,1590.0,1691.0,0.0,...,408.0,481.0,565.0,690.0,915.0,61.5,-1.2,12.1,-1.5,NaN
1992,4673.0,3232.0,1441.0,373.0,93.0,975.0,3222.0,2190.0,764.0,0.0,...,409.0,475.0,562.0,687.0,919.5,60.0,-3.1,13.1,2.3,1217.0
1993,4282.0,3126.0,1156.0,496.0,81.0,579.0,2988.0,2306.0,642.0,0.0,...,412.0,482.0,571.0,719.0,923.9,60.1,-0.6,14.3,2.1,1676.0
1994,4748.0,3358.0,1390.0,518.0,99.0,773.0,3304.0,2493.0,671.0,0.0,...,421.0,485.0,579.0,711.0,926.9,60.1,1.7,13.5,-0.8,409.0
1995,4168.0,3040.0,1128.0,417.0,72.0,639.0,2695.0,2098.0,570.0,24.0,...,422.0,488.0,584.0,760.0,928.1,59.4,0.9,12.2,0.3,-432.0
1996,4059.0,3278.0,781.0,447.0,59.0,275.0,2806.0,2527.0,279.0,0.0,...,421.0,488.0,588.0,732.0,931.3,59.4,0.2,12.4,-2.5,1475.0
1997,3813.0,2939.0,874.0,303.0,58.0,513.0,2732.0,2225.0,479.0,0.0,...,424.0,490.0,589.0,722.0,932.4,59.7,1.5,12.1,1.4,695.0
1998,3137.0,2257.0,880.0,290.0,89.0,501.0,2171.0,1664.0,418.0,89.0,...,433.0,496.0,603.0,763.0,931.8,60.5,3.6,10.5,3.8,-547.0
1999,4250.0,3345.0,905.0,218.0,29.0,658.0,2834.0,2263.0,571.0,0.0,...,448.0,507.0,609.0,761.0,933.8,60.8,2.0,9.6,4.4,1991.0
2000,4432.0,2856.0,1576.0,266.0,17.0,1293.0,3050.0,1867.0,810.0,371.0,...,468.0,522.0,621.0,773.0,933.8,61.2,2.0,9.1,-0.6,126.0
2001,4092.0,2761.0,1331.0,228.0,40.0,1063.0,2767.0,1765.0,746.0,256.0,...,486.0,537.0,645.0,835.0,932.5,62.0,0.9,9.7,2.8,-946.0
2002,4970.0,3363.0,1607.0,253.0,144.0,1210.0,3721.0,2493.0,847.0,378.0,...,499.0,555.0,669.0,897.0,935.2,62.5,1.7,9.6,2.6,1055.0
2003,5096.0,2968.0,2128.0,338.0,277.0,1513.0,3591.0,2219.0,833.0,530.0,...,514.0,575.0,684.0,919.0,937.7,63.0,2.1,9.1,0.0,993.0
2004,4717.0,3270.0,1447.0,266.0,186.0,995.0,3314.0,2310.0,559.0,445.0,...,532.0,592.0,711.0,973.0,939.6,63.9,2.4,8.8,1.5,652.0
2005,4775.0,3010.0,1765.0,301.0,265.0,1199.0,3257.0,2133.0,643.0,481.0,...,532.0,608.0,726.0,912.0,937.9,63.4,0.1,8.4,0.9,-2754.0
2006,4896.0,2757.0,2139.0,353.0,255.0,1531.0,3327.0,1941.0,1096.0,290.0,...,553.0,629.0,760.0,986.0,937.9,62.7,-0.2,7.9,3.5,-1145.0
2007,4750.0,2887.0,1863.0,333.0,221.0,1309.0,3320.0,2075.0,911.0,334.0,...,557.0,642.0,777.0,1030.0,935.1,63.6,1.4,8.0,2.1,-2087.0
2008,3982.0,2636.0,1346.0,328.0,219.0,799.0,3327.0,2509.0,647.0,171.0,...,580.0,664.0,795.0,1030.0,935.9,63.7,1.0,7.6,3.6,938.0
2009,3438.0,2193.0,1245.0,274.0,187.0,784.0,2787.0,2037.0,655.0,95.0,...,617.0,692.0,838.0,1056.0,938.2,64.2,-0.5,9.2,4.0,2486.0
2010,4309.0,2392.0,1917.0,373.0,200.0,1344.0,3538.0,2321.0,1119.0,98.0,...,612.0,713.0,851.0,1116.0,942.1,64.3,0.4,9.6,2.9,4100.0
2011,4644.0,2045.0,2599.0,418.0,241.0,1940.0,4075.0,2113.0,1793.0,169.0,...,647.0,730.0,882.0,1146.0,944.5,63.9,0.4,9.0,-0.2,3069.0
2012,4522.0,2258.0,2264.0,420.0,218.0,1626.0,3925.0,2262.0,1482.0,181.0,...,663.0,750.0,909.0,1153.0,944.9,64.4,1.0,9.1,1.6,-88.0
2013,3919.0,1639.0,2280.0,332.0,259.0,1689.0,3314.0,1676.0,1564.0,74.0,...,682.0,763.0,929.0,1200.0,943.5,63.7,-1.1,9.1,2.5,-1647.0
2014,3056.0,1355.0,1701.0,220.0,179.0,1302.0,2633.0,1326.0,1089.0,166.0,...,686.0,776.0,955.0,1231.0,943.3,62.8,-1.1,9.0,0.4,-238.0
2015,3825.0,1350.0,2475.0,259.0,129.0,2087.0,3448.0,1293.0,1611.0,386.0,...,702.0,807.0,992.0,1262.0,943.4,62.4,0.1,8.6,2.5,284.0
2016,3767.0,1656.0,2111.0,318.0,144.0,1649.0,3118.0,1397.0,1409.0,312.0,...,724.0,819.0,1008.0,1254.0,949.5,61.7,-0.4,8.3,NaN,6494.0

In [10]:
# Look at info for table
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, 1990 to 2016
Data columns (total 35 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Starts, total                                        27 non-null     object
 1   Starts, Single-detached                              27 non-null     object
 2    Starts,  Multiple                                   27 non-null     object
 3   Starts,    Semi-detached                             27 non-null     object
 4   Starts,     Row                                      27 non-null     object
 5   Starts,      Apartment                               27 non-null     object
 6   Starts by intended market, 1 total                   27 non-null     object
 7   Starts,  Homeownership - freehold                    27 non-null     object
 8   Starts,   Rental                                     27 non-null     object
 9   Starts,   Homeownership - condominium                27 non-null     object
 10  Starts,   Other (co-op and unknown)                  27 non-null     object
 11  Completions, total                                   27 non-null     object
 12  Residential Building Permits4                        27 non-null     object
 13  Residential Building Permits($) (thousands)4         27 non-null     object
 14  Supply, Newly completed and unabsorbed homes         25 non-null     object
 15  Supply,  Single- and semi-detached                   25 non-null     object
 16  Supply, Row and apartment                            25 non-null     object
 17  Rental vacancy rate (%)3                             27 non-null     object
 18  Rental availability rate (%)3                        12 non-null     object
 19  Vacancy Rate (Standard Spaces) in Seniors' Rental 6  8 non-null      object
 20  New Housing Price Index (% change)5                  27 non-null     object
 21  Consumer Price Index (% change)5                     27 non-null     object
 22  Construction Wage Rate Index (% change)5             19 non-null     object
 23  Owned accommodation costs (% change)5                27 non-null     object
 24  Rental accommodation costs (% change)5               27 non-null     object
 25  Average rent ($)  Bachelor                           27 non-null     object
 26  Average rent ($)  One-bedroom                        27 non-null     object
 27  Average rent ($)  Two-bedroom                        27 non-null     object
 28  Average rent ($)  3+ bedroom                         27 non-null     object
 29  Population on July 1 (thousands)4                    27 non-null     object
 30  Labour force participation rate (%)4                 27 non-null     object
 31  Employment (% change)5                               27 non-null     object
 32  Unemployment rate (%)4                               27 non-null     object
 33  Real disposable income (% change)5                   25 non-null     object
 34  Net migration5                                       25 non-null     object
dtypes: object(35)
memory usage: 7.6+ KB

In [11]:
# Rename columns for clarity
df = df.rename(columns={
    'Starts, total' : 'total_starts',
    'Starts, Single-detached':'single_detached_starts',
    ' Starts,  Multiple':'multiple_starts',
    'Starts,    Semi-detached':'semi_detached_starts',
    'Starts,     Row':'row_starts',
    'Starts,      Apartment':'apartment_starts',
    'Starts by intended market, 1 total':'starts_by_market',
    'Starts,  Homeownership - freehold':'freehold_homeownership_starts',
    'Starts,   Rental':'rental_starts',
    'Starts,   Homeownership - condominium':'condominium_ownership_starts',
    'Starts,   Other (co-op and unknown)':'co_op_and_unknown_starts',
    'Completions, total':'total_completions',
    'Residential Building Permits4':'residential_building_permits',
    'Residential Building Permits($) (thousands)4':'res_bldg_permit_value_thousands',
    'Supply, Newly completed and unabsorbed homes':'new_completed_and_unabsorbed_home_supply',
    'Supply,  Single- and semi-detached':'single_and_semi_detached_supply',
    'Supply, Row and apartment':'row_and_apartment_supply',
    'Rental vacancy rate (%)3':'rental_vacancy_percent',
    'Rental availability rate (%)3':'rental_availabilty_rate_percent',
    'Vacancy Rate (Standard Spaces) in Seniors\' Rental 6':'standard_space_seniors_vacancy_rate',
    'New Housing Price Index (% change)5':'pct_change_new_housing_price_index',
    'Consumer Price Index (% change)5':'pct_change_consumer_price_index',
    'Construction Wage Rate Index (% change)5':'pct_change_construction_wage_rate_index',
    'Owned accommodation costs (% change)5':'pct_change_owned_accommodation_costs',
    'Rental accommodation costs (% change)5':'pct_change_rental_accommodation_costs',
    'Average rent ($)  Bachelor':'bachelor_average_rent_dollars',
    'Average rent ($)  One-bedroom':'one_bedroom_average_rent',
    'Average rent ($)  Two-bedroom':'two_bed_average_rent_dollars',
    'Average rent ($)  3+ bedroom':'three_plus_bed_average_rent_dollars',
    'Population on July 1 (thousands)4':'july_1_population_thousands',
    'Labour force participation rate (%)4':'labour_force_participation_rate_percent',
    'Employment (% change)5':'pct_change_employment',
    'Unemployment rate (%)4':'pct_change_unemployment',
    'Real disposable income (% change)5':'pct_change_real_disposable_income',
    'Net migration5':'net_migration',
})

In [12]:
# Check info of dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, 1990 to 2016
Data columns (total 35 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   total_starts                              27 non-null     object
 1   single_detached_starts                    27 non-null     object
 2   multiple_starts                           27 non-null     object
 3   semi_detached_starts                      27 non-null     object
 4   row_starts                                27 non-null     object
 5   apartment_starts                          27 non-null     object
 6   starts_by_market                          27 non-null     object
 7   freehold_homeownership_starts             27 non-null     object
 8   rental_starts                             27 non-null     object
 9   condominium_ownership_starts              27 non-null     object
 10  co_op_and_unknown_starts                  27 non-null     object
 11  total_completions                         27 non-null     object
 12  residential_building_permits              27 non-null     object
 13  res_bldg_permit_value_thousands           27 non-null     object
 14  new_completed_and_unabsorbed_home_supply  25 non-null     object
 15  single_and_semi_detached_supply           25 non-null     object
 16  row_and_apartment_supply                  25 non-null     object
 17  rental_vacancy_percent                    27 non-null     object
 18  rental_availabilty_rate_percent           12 non-null     object
 19  standard_space_seniors_vacancy_rate       8 non-null      object
 20  pct_change_new_housing_price_index        27 non-null     object
 21  pct_change_consumer_price_index           27 non-null     object
 22  pct_change_construction_wage_rate_index   19 non-null     object
 23  pct_change_owned_accommodation_costs      27 non-null     object
 24  pct_change_rental_accommodation_costs     27 non-null     object
 25  bachelor_average_rent_dollars             27 non-null     object
 26  one_bedroom_average_rent                  27 non-null     object
 27  two_bed_average_rent_dollars              27 non-null     object
 28  three_plus_bed_average_rent_dollars       27 non-null     object
 29  july_1_population_thousands               27 non-null     object
 30  labour_force_participation_rate_percent   27 non-null     object
 31  pct_change_employment                     27 non-null     object
 32  pct_change_unemployment                   27 non-null     object
 33  pct_change_real_disposable_income         25 non-null     object
 34  net_migration                             25 non-null     object
dtypes: object(35)
memory usage: 7.6+ KB

In [13]:
# Change columns with object type to numeric
df['total_starts'] = pd.to_numeric(df['total_starts'], downcast='float', errors='coerce')
df['single_detached_starts'] = pd.to_numeric(df['single_detached_starts'], downcast='float', errors='coerce')
df['multiple_starts'] = pd.to_numeric(df['multiple_starts'], downcast='float', errors='coerce')
df['semi_detached_starts'] = pd.to_numeric(df['semi_detached_starts'], downcast='float', errors='coerce')
df['row_starts'] = pd.to_numeric(df['row_starts'], downcast='float', errors='coerce')
df['rental_starts'] = pd.to_numeric(df['rental_starts'], downcast='float', errors='coerce')
df['apartment_starts'] = pd.to_numeric(df['apartment_starts'], downcast='float', errors='coerce')
df['starts_by_market'] = pd.to_numeric(df['starts_by_market'], downcast='float', errors='coerce')
df['freehold_homeownership_starts'] = pd.to_numeric(df['freehold_homeownership_starts'], downcast='float', errors='coerce')
df['condominium_ownership_starts'] = pd.to_numeric(df['condominium_ownership_starts'], downcast='float', errors='coerce')
df['co_op_and_unknown_starts'] = pd.to_numeric(df['co_op_and_unknown_starts'], downcast='float', errors='coerce')
df['total_completions'] = pd.to_numeric(df['total_completions'], downcast='float', errors='coerce')
df['residential_building_permits'] = pd.to_numeric(df['residential_building_permits'], downcast='float', errors='coerce')
df['res_bldg_permit_value_thousands'] = pd.to_numeric(df['res_bldg_permit_value_thousands'], downcast='float', errors='coerce')
df['new_completed_and_unabsorbed_home_supply'] = pd.to_numeric(df['new_completed_and_unabsorbed_home_supply'], downcast='float', errors='coerce')
df['single_and_semi_detached_supply'] = pd.to_numeric(df['single_and_semi_detached_supply'], downcast='float', errors='coerce')
df['row_and_apartment_supply'] = pd.to_numeric(df['row_and_apartment_supply'], downcast='float', errors='coerce')
df['rental_vacancy_percent'] = pd.to_numeric(df['rental_vacancy_percent'], downcast='float', errors='coerce')
df['rental_availabilty_rate_percent'] = pd.to_numeric(df['rental_availabilty_rate_percent'], downcast='float', errors='coerce')
df['standard_space_seniors_vacancy_rate'] = pd.to_numeric(df['standard_space_seniors_vacancy_rate'], downcast='float', errors='coerce')
df['pct_change_new_housing_price_index'] = pd.to_numeric(df['pct_change_new_housing_price_index'], downcast='float', errors='coerce')
df['pct_change_consumer_price_index'] = pd.to_numeric(df['pct_change_consumer_price_index'], downcast='float', errors='coerce')
df['pct_change_construction_wage_rate_index'] = pd.to_numeric(df['pct_change_construction_wage_rate_index'], downcast='float', errors='coerce')
df['pct_change_owned_accommodation_costs'] = pd.to_numeric(df['pct_change_owned_accommodation_costs'], downcast='float', errors='coerce')
df['pct_change_rental_accommodation_costs'] = pd.to_numeric(df['pct_change_rental_accommodation_costs'], downcast='float', errors='coerce')
df['bachelor_average_rent_dollars'] = pd.to_numeric(df['bachelor_average_rent_dollars'], downcast='float', errors='coerce')
df['one_bedroom_average_rent'] = pd.to_numeric(df['one_bedroom_average_rent'], downcast='float', errors='coerce')
df['two_bed_average_rent_dollars'] = pd.to_numeric(df['two_bed_average_rent_dollars'], downcast='float', errors='coerce')
df['three_plus_bed_average_rent_dollars'] = pd.to_numeric(df['three_plus_bed_average_rent_dollars'], downcast='float', errors='coerce')
df['july_1_population_thousands'] = pd.to_numeric(df['july_1_population_thousands'], downcast='float', errors='coerce')
df['labour_force_participation_rate_percent'] = pd.to_numeric(df['labour_force_participation_rate_percent'], downcast='float', errors='coerce')
df['pct_change_employment'] = pd.to_numeric(df['pct_change_employment'], downcast='float', errors='coerce')
df['pct_change_unemployment'] = pd.to_numeric(df['pct_change_unemployment'], downcast='float', errors='coerce')
df['pct_change_real_disposable_income'] = pd.to_numeric(df['pct_change_real_disposable_income'], downcast='float', errors='coerce')
df['net_migration'] = pd.to_numeric(df['net_migration'], downcast='float', errors='coerce')

In [14]:
# Check info
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, 1990 to 2016
Data columns (total 35 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   total_starts                              27 non-null     float32
 1   single_detached_starts                    27 non-null     float32
 2   multiple_starts                           27 non-null     float32
 3   semi_detached_starts                      27 non-null     float32
 4   row_starts                                27 non-null     float32
 5   apartment_starts                          27 non-null     float32
 6   starts_by_market                          27 non-null     float32
 7   freehold_homeownership_starts             27 non-null     float32
 8   rental_starts                             27 non-null     float32
 9   condominium_ownership_starts              27 non-null     float32
 10  co_op_and_unknown_starts                  27 non-null     float32
 11  total_completions                         27 non-null     float32
 12  residential_building_permits              27 non-null     float32
 13  res_bldg_permit_value_thousands           27 non-null     float32
 14  new_completed_and_unabsorbed_home_supply  25 non-null     float32
 15  single_and_semi_detached_supply           25 non-null     float32
 16  row_and_apartment_supply                  25 non-null     float32
 17  rental_vacancy_percent                    27 non-null     float32
 18  rental_availabilty_rate_percent           12 non-null     float32
 19  standard_space_seniors_vacancy_rate       8 non-null      float32
 20  pct_change_new_housing_price_index        27 non-null     float32
 21  pct_change_consumer_price_index           27 non-null     float32
 22  pct_change_construction_wage_rate_index   19 non-null     float32
 23  pct_change_owned_accommodation_costs      27 non-null     float32
 24  pct_change_rental_accommodation_costs     27 non-null     float32
 25  bachelor_average_rent_dollars             27 non-null     float32
 26  one_bedroom_average_rent                  27 non-null     float32
 27  two_bed_average_rent_dollars              27 non-null     float32
 28  three_plus_bed_average_rent_dollars       27 non-null     float32
 29  july_1_population_thousands               27 non-null     float32
 30  labour_force_participation_rate_percent   27 non-null     float32
 31  pct_change_employment                     27 non-null     float32
 32  pct_change_unemployment                   27 non-null     float32
 33  pct_change_real_disposable_income         25 non-null     float32
 34  net_migration                             25 non-null     float32
dtypes: float32(35)
memory usage: 3.9+ KB

# 04 Consistency Checks

In [15]:
# Check for mixed data types in Housing table
for col in df.columns.tolist():
    weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis=1)
    if len (df[weird]) > 0:
        print(col)

#### There are no mixed-type data columns in the dataframe.

In [16]:
# Check for missing observations in dataframe
df.isnull().sum()

indicator
total_starts                                 0
single_detached_starts                       0
multiple_starts                              0
semi_detached_starts                         0
row_starts                                   0
apartment_starts                             0
starts_by_market                             0
freehold_homeownership_starts                0
rental_starts                                0
condominium_ownership_starts                 0
co_op_and_unknown_starts                     0
total_completions                            0
residential_building_permits                 0
res_bldg_permit_value_thousands              0
new_completed_and_unabsorbed_home_supply     2
single_and_semi_detached_supply              2
row_and_apartment_supply                     2
rental_vacancy_percent                       0
rental_availabilty_rate_percent             15
standard_space_seniors_vacancy_rate         19
pct_change_new_housing_price_index           0
pct_change_consumer_price_index              0
pct_change_construction_wage_rate_index      8
pct_change_owned_accommodation_costs         0
pct_change_rental_accommodation_costs        0
bachelor_average_rent_dollars                0
one_bedroom_average_rent                     0
two_bed_average_rent_dollars                 0
three_plus_bed_average_rent_dollars          0
july_1_population_thousands                  0
labour_force_participation_rate_percent      0
pct_change_employment                        0
pct_change_unemployment                      0
pct_change_real_disposable_income            2
net_migration                                2
dtype: int64

#### Some columns are missing data, however having examined the table in Excel, this is because that variable was not measured every year. No action will be taken.

In [17]:
# Look for full duplicates in the dataframe
df_dups2 = df[df.duplicated()]
df_dups2

Empty DataFrame
Columns: [total_starts, single_detached_starts, multiple_starts, semi_detached_starts, row_starts, apartment_starts, starts_by_market, freehold_homeownership_starts, rental_starts, condominium_ownership_starts, co_op_and_unknown_starts, total_completions, residential_building_permits, res_bldg_permit_value_thousands, new_completed_and_unabsorbed_home_supply, single_and_semi_detached_supply, row_and_apartment_supply, rental_vacancy_percent, rental_availabilty_rate_percent, standard_space_seniors_vacancy_rate, pct_change_new_housing_price_index, pct_change_consumer_price_index, pct_change_construction_wage_rate_index, pct_change_owned_accommodation_costs, pct_change_rental_accommodation_costs, bachelor_average_rent_dollars, one_bedroom_average_rent, two_bed_average_rent_dollars, three_plus_bed_average_rent_dollars, july_1_population_thousands, labour_force_participation_rate_percent, pct_change_employment, pct_change_unemployment, pct_change_real_disposable_income, net_migration]
Index: []

[0 rows x 35 columns]

#### There are no duplicates in the dataframe.

In [18]:
# Compute descriptive statistics
df.describe()

indicator,total_starts,single_detached_starts,multiple_starts,semi_detached_starts,row_starts,apartment_starts,starts_by_market,freehold_homeownership_starts,rental_starts,condominium_ownership_starts,...,bachelor_average_rent_dollars,one_bedroom_average_rent,two_bed_average_rent_dollars,three_plus_bed_average_rent_dollars,july_1_population_thousands,labour_force_participation_rate_percent,pct_change_employment,pct_change_unemployment,pct_change_real_disposable_income,net_migration
count,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,...,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,25.000000,25.000000
mean,4335.296387,2674.592529,1660.703735,331.592590,144.703705,1184.407349,3207.222168,2047.851807,926.148132,180.074081,...,527.518494,600.962952,723.740723,925.037048,934.377808,62.103703,0.600000,10.022223,1.584000,711.039978
std,608.867310,642.001038,541.452515,79.938087,82.190117,510.973236,437.948364,361.254089,421.046570,172.502808,...,106.787483,117.944412,149.530441,199.616837,9.247217,1.645152,1.396149,1.860176,1.817434,1978.330811
min,3056.000000,1350.000000,781.000000,218.000000,17.000000,275.000000,2171.000000,1293.000000,279.000000,0.000000,...,391.000000,460.000000,539.000000,658.000000,910.500000,59.400002,-3.100000,7.600000,-2.500000,-2754.000000
25%,3950.500000,2257.500000,1288.000000,270.000000,76.500000,778.500000,2820.000000,1816.000000,642.500000,6.000000,...,423.000000,489.000000,588.500000,746.000000,931.549988,60.650000,-0.300000,8.900000,0.300000,-432.000000
50%,4309.000000,2856.000000,1607.000000,318.000000,144.000000,1210.000000,3304.000000,2133.000000,810.000000,166.000000,...,514.000000,575.000000,684.000000,912.000000,935.200012,62.400002,0.900000,9.200000,2.100000,652.000000
75%,4749.000000,3179.000000,2119.500000,373.000000,218.500000,1522.000000,3493.000000,2284.500000,1113.000000,323.000000,...,614.500000,702.500000,844.500000,1086.000000,940.849976,63.650000,1.600000,11.400000,2.800000,1475.000000
max,5560.000000,3639.000000,2599.000000,518.000000,277.000000,2222.000000,4075.000000,2527.000000,1793.000000,530.000000,...,724.000000,819.000000,1008.000000,1262.000000,949.500000,64.400002,3.600000,14.300000,4.400000,6494.000000

In [19]:
df.describe().to_clipboard()

In [20]:
# Check final shape
df.shape

(27, 35)

# 05 Export Dataframe

In [21]:
# Export data to pkl
df.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'NSHousing_cleaned.pkl'))